# Generated by Django 3.1.1 on 2020-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200905_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_pic'),
        ),
    ]
