# Generated by Django 3.1.1 on 2020-09-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200908_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalblog',
            name='date',
        ),
    ]
