# Generated by Django 3.1.2 on 2020-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201022_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
