# Generated by Django 3.1.2 on 2020-10-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201012_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalreply',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reply',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
