# Generated by Django 3.1.1 on 2020-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201001_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbmail',
            field=models.ImageField(blank=True, default='default_thumbnail.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='thumbmail',
            field=models.TextField(blank=True, default='default_thumbnail.png', max_length=100),
        ),
    ]
