# Generated by Django 3.1.1 on 2020-10-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201007_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbmail',
        ),
        migrations.RemoveField(
            model_name='historicalblog',
            name='thumbmail',
        ),
    ]
