# Generated by Django 3.1.2 on 2020-10-19 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20201019_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='is_public',
            new_name='is_closed',
        ),
        migrations.AlterField(
            model_name='issue',
            name='blog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('CODE', 'Code'), ('SYSTEM', 'System'), ('TYPO', 'Typo'), ('ETC', 'Etc')], default='Etc', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
