# Generated by Django 3.1.1 on 2020-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201007_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_thumbnail.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalblog',
            name='thumbnail',
            field=models.TextField(blank=True, default='default_thumbnail.png', max_length=100),
        ),
    ]
