# Generated by Django 3.1.2 on 2020-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201007_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog', width_field='600')),
            ],
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='en',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='th',
        ),
    ]
